#!/bin/bash

set -e	# better to exit on an error then to let it fuck shit up

# This script is used to quickly set up my_env on a system that I've cloned the repo into.
# I use this setup across many of the servers, and systems I'm on, because damnit I like
# my setup a whole lot.

# Basic usage is simple, clone or download the repo into your home directory, then run this setup script

# set some variables
home=$HOME	# gonna use this throughout
dropbox="Dropbox"	# setting just in case dropbox is different folder, I can change this var

cd "${home}"	# let's go to home directory to do all this work

clear # want to see the output on it's own
printf "\n\n"
echo "========================================="
echo "Setup Started."
echo "========================================="
printf "\n\n"

# check if there is a symlink before copying them, if they are, don't copy, if they are not, then copy
function checkthencopy () 
{
	if [[ -h "${home}/$1" ]]; then
		echo "$1 is already a symlink, skipping cp"
	else
		cp "${home}/$1" "${home}/$1_orig" && { echo "Original $1 successfully copied to $1_orig"; } || { echo "Original $1 not copied. You need to check out why."; }
	fi
}

# Check if there is a dropbox folder (because I keep my_env files in dropbox) but on servers and other systems where
# i'm not using dropbox, I need to use just the local user folder without dropbox in the mix
if [ -d "${home}/${dropbox}/" ]; then
	myenvrootdir="${home}/${dropbox}/"
else
	myenvrootdir="${home}/"
fi

# run checks and copy if needed for backup
checkthencopy .bashrc
checkthencopy .vim
checkthencopy .vimrc

# remove originals
rm ~/.bashrc && { echo "Original .bashrc removed"; } || { echo "Error removing original .bashrc"; }
rm -r ~/.vim && { echo "Original .vim removed"; } || { echo "Error removing original .vim"; }
rm ~/.vimrc && { echo "Original .vimrc removed"; } || { echo "Error removing original .vimrc"; }

# symlink to my_env files
ln -s "${myenvrootdir}my_env/bash/bashrc" .bashrc && { echo "Symlink to .bashrc in my_env/bash successful"; } || { echo "Symlink to my_env/.bashrc not made"; }  
ln -s "${myenvrootdir}my_env/vim/" .vim && { echo "Symlink to .vim in my_env/ successful"; } || { echo "Symlink to my_env/.vim not made"; }
ln -s "${myenvrootdir}my_env/vim/vimrc" .vimrc && { echo "Symlink to .vimrc in my_env/ successful"; } || { echo "Symlink to my_env/.vimrc not made"; }

printf "\n\n"
echo "========================================="
echo "Setup Completed."
echo "Check the output for any errors and correct manually if needed."
echo "========================================="
printf "\n\n"
