#!/bin/bash

echo "========================================="
echo "Setup Started."
echo "========================================="

dropbox="Dropbox"

if [ -d ~/"$dropbox"/ ]; then
	myenvrootdir="~/Dropbox/"
else
	myenvrootdir="~/"
fi

cd ~ && { echo "In home directory"; } || { echo "Dude, we didn't make it into your home directory. We're gonna have some problems."; }

# copy files
cp ~/.bashrc ~/.bashrc_orig && { echo "Original .bashrc successfully copied to .bashrc_orig"; } || { echo "Original .bashrc not copied"; }
cp -r ~/.vim ~/.vim_orig && { echo "Original.vim copied successufully to .vim_orig"; } || { echo "Original .vim not copied"; }
cp ~/.vimrc ~/.vimrc_orig && { echo "Original .vimrc copied successfully to .vimrc_orig"; } || { echo "Original .vimrc not copied"; }

# remove originals
rm ~/.bashrc && { echo "Original .bashrc removed"; } || { echo "Error removing original .bashrc"; }
rm -r ~/.vim && { echo "Original .vim removed"; } || { echo "Error removing original .vim"; }
rm ~/.vimrc && { echo "Original .vimrc removed"; } || { echo "Error removing original .vimrc"; }

# symlink to my_env files
ln -s ${myenvrootdir}my_env/bash/bashrc .bashrc && { echo "Symlink to .bashrc in my_env/bash successful"; } || { echo "Symlink to my_env/.bashrc not made"; }  
ln -s ${myenvrootdir}my_env/vim/ .vim && { echo "Symlink to .vim in my_env/ successful"; } || { echo "Symlink to my_env/.vim not made"; }
ln -s ${myenvrootdir}my_env/vim/vimrc .vimrc && { echo "Symlink to .vimrc in my_env/ successful"; } || { echo "Symlink to my_env/.vimrc not made"; }

echo "========================================="
echo "Setup Completed."
echo "Check the output for any errors and correct manually if needed."
echo "========================================="
