# each of the main functions of the bashrc broken down into 
# separate files for easy management

# handles environment variables
. ~/my_env/bash/env

# handles configurations
. ~/my_env/bash/config

# handles my aliases
. ~/my_env/bash/aliases

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Added for android studio - fastboot and adb - quick access
if [ -d "<path-to-sdk>/platform-tools" ] ; then
	  export PATH="<path-to-sdk>/platform-tools:$PATH"
fi
